name: Snake animation

on:
  schedule: # runs every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate snake animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: zignd
          svg_out_path: dist/github-contribution-grid-snake.svg
